import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { signIn, signOut, useSession } from "next-auth/client";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const [session, loading] = useSession();


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
				{!session &&  (
					<>
					Not Signed In <br />
					<button onClick={signIn}>Sign In</button>
					</>
				)}
				{session && (
					<>
					Signed In as {session.user.email} <br />
					<div>You can now access secret pages</div>
					<button>
						<Link href='/secret'>To the secret</Link>
					</button>
					<button onClick={signOut}>Sign Out</button>
					</>
				)}
            </main>
        </div>
    );
};

export default Home;
